version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodbtp
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-network

  books:
    build:
      context: ./books
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://db:27017/books
    ports:
      - "7000:7000"
    depends_on:
      - db
    networks:
      - microservices-network

  customers:
    build:
      context: ./customers
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://db:27017/customers
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - microservices-network

  orders:
    build:
      context: ./orders
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://db:27017/orders
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - microservices-network

networks:
  microservices-network:

volumes:
  mongo_data:
